<a href="https://colab.research.google.com/github/AshRK1997/Titanic_Kaggle/blob/master/Titanic_kaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!unzip titanic.zip

Archive:  titanic.zip
  inflating: gender_submission.csv   
  inflating: test.csv                
  inflating: train.csv               


In [ ]:

import pandas as pd
import numpy as np

data_train = pd.read_csv('train.csv')
data_test = pd.read_csv('test.csv')

y = data_train['Survived'].values
y = y.reshape(len(y),1)

In [ ]:
x = data_train

x.drop('Survived',axis=1,inplace=True)
x.drop('Name',axis=1,inplace=True)
x.drop('Ticket',axis=1,inplace=True)
x.drop('PassengerId',axis=1,inplace=True)
x.drop('Cabin',axis=1,inplace=True)

x.replace(r'^\s*$', np.NaN, regex=True, inplace=True)
x.replace("", np.NaN, inplace=True)

print(x.head(20))

    Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0        3    male  22.0      1      0   7.2500        S
1        1  female  38.0      1      0  71.2833        C
2        3  female  26.0      0      0   7.9250        S
3        1  female  35.0      1      0  53.1000        S
4        3    male  35.0      0      0   8.0500        S
5        3    male   NaN      0      0   8.4583        Q
6        1    male  54.0      0      0  51.8625        S
7        3    male   2.0      3      1  21.0750        S
8        3  female  27.0      0      2  11.1333        S
9        2  female  14.0      1      0  30.0708        C
10       3  female   4.0      1      1  16.7000        S
11       1  female  58.0      0      0  26.5500        S
12       3    male  20.0      0      0   8.0500        S
13       3    male  39.0      1      5  31.2750        S
14       3  female  14.0      0      0   7.8542        S
15       2  female  55.0      0      0  16.0000        S
16       3    male   2.0      4

In [ ]:
x_test_final = data_test

x_test_final.drop('Name',axis=1,inplace=True)
x_test_final.drop('Ticket',axis=1,inplace=True)
x_test_final.drop('PassengerId',axis=1,inplace=True)
x_test_final.drop('Cabin',axis=1,inplace=True)

x_test_final.replace(r'^\s*$', np.NaN, regex=True, inplace=True)
x_test_final.replace("", np.NaN, inplace=True)

In [ ]:
x_test_final['Embarked'].replace(np.nan, "None", inplace=True)
x['Embarked'].replace(np.NaN, "None", inplace=True)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encode_embark = OneHotEncoder(categories='auto')
enc_embark = pd.DataFrame(encode_embark.fit_transform(x['Embarked'].values.reshape(-1,1)).toarray())

x.drop('Embarked',axis=1,inplace=True)
x = pd.concat([x,enc_embark],axis=1)

enc_embark = pd.DataFrame(encode_embark.transform(x_test_final['Embarked'].values.reshape(-1,1)).toarray())

x_test_final.drop('Embarked',axis=1,inplace=True)
x_test_final = pd.concat([x_test_final,enc_embark],axis=1)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

x['Sex'] = le.fit_transform(x['Sex'])
x_test_final['Sex'] = le.transform(x_test_final['Sex'])

print(x,x_test_final)

     Pclass  Sex   Age  SibSp  Parch     Fare    0    1    2    3
0         3    1  22.0      1      0   7.2500  0.0  0.0  0.0  1.0
1         1    0  38.0      1      0  71.2833  1.0  0.0  0.0  0.0
2         3    0  26.0      0      0   7.9250  0.0  0.0  0.0  1.0
3         1    0  35.0      1      0  53.1000  0.0  0.0  0.0  1.0
4         3    1  35.0      0      0   8.0500  0.0  0.0  0.0  1.0
..      ...  ...   ...    ...    ...      ...  ...  ...  ...  ...
886       2    1  27.0      0      0  13.0000  0.0  0.0  0.0  1.0
887       1    0  19.0      0      0  30.0000  0.0  0.0  0.0  1.0
888       3    0   NaN      1      2  23.4500  0.0  0.0  0.0  1.0
889       1    1  26.0      0      0  30.0000  1.0  0.0  0.0  0.0
890       3    1  32.0      0      0   7.7500  0.0  0.0  1.0  0.0

[891 rows x 10 columns]      Pclass  Sex   Age  SibSp  Parch      Fare    0    1    2    3
0         3    1  34.5      0      0    7.8292  0.0  0.0  1.0  0.0
1         3    0  47.0      1      0    7.0000  0

In [ ]:
from sklearn.impute import SimpleImputer

x = np.array(x)
x_test_final = np.array(x_test_final)

imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

imputer.fit(x[:, 2:3])

x[:, 2:3] = imputer.transform(x[:, 2:3])
x_test_final[:, 2:3] = imputer.transform(x_test_final[:, 2:3])

impute = SimpleImputer(missing_values=np.nan, strategy='mean')
impute.fit(x[:,5:6])
x_test_final[:, 5:6] = imputer.transform(x_test_final[:, 5:6])

print(x,x_test_final)

[[ 3.  1. 22. ...  0.  0.  1.]
 [ 1.  0. 38. ...  0.  0.  0.]
 [ 3.  0. 26. ...  0.  0.  1.]
 ...
 [ 3.  0. 24. ...  0.  0.  1.]
 [ 1.  1. 26. ...  0.  0.  0.]
 [ 3.  1. 32. ...  0.  1.  0.]] [[ 3.   1.  34.5 ...  0.   1.   0. ]
 [ 3.   0.  47.  ...  0.   0.   1. ]
 [ 2.   1.  62.  ...  0.   1.   0. ]
 ...
 [ 3.   1.  38.5 ...  0.   0.   1. ]
 [ 3.   1.  24.  ...  0.   0.   1. ]
 [ 3.   1.  24.  ...  0.   0.   0. ]]


In [ ]:
x = pd.DataFrame(x)
x_test_final = pd.DataFrame(x_test_final)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [ ]:
x_test_scaled.shape

(90, 10)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=8)
principalComponents_train = pca.fit_transform(x_train_scaled)
principalComponents_test = pca.transform(x_test_scaled)
x_train_pca = pd.DataFrame(data = principalComponents_train)
#             , columns = ['principal component 1', 'principal component 2'])
x_test_pca = pd.DataFrame(data = principalComponents_test)
#             , columns = ['principal component 1', 'principal component 2'])

print(sum(pca.explained_variance_ratio_))

0.964246400694233


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

check_grad = GradientBoostingClassifier(learning_rate=0.05,n_estimators=80)
check_grad.fit(x_train_scaled,y_train)
print(check_grad.score(x_test_scaled,y_test))

0.8333333333333334


/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.neural_network import MLPClassifier

check_mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(8), random_state=0,max_iter=700)
check_mlp.fit(x_train_scaled,y_train)
print(check_mlp.score(x_test_scaled,y_test))

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.8333333333333334


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [ ]:
from sklearn.neural_network import MLPClassifier

check_mlp = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(8), random_state=0,max_iter=1000)
check_mlp.fit(x_train_pca,y_train)
print(check_mlp.score(x_test_pca,y_test))

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.8333333333333334


In [ ]:
from xgboost import XGBClassifier

check_xgb = XGBClassifier(learning_rate=0.1)
check_xgb.fit(x_train_scaled,y_train)
print(check_xgb.score(x_test_scaled,y_test))

0.8222222222222222


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.linear_model import LogisticRegression

check_log = LogisticRegression(max_iter=1000, C=0.01)
check_log.fit(x_train_scaled, y_train)
print(check_log.score(x_test_scaled,y_test))

0.8222222222222222


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.svm import SVC

check_svm = SVC(kernel = 'rbf')
check_svm.fit(x_train_scaled, y_train)
print(check_svm.score(x_test_scaled,y_test))

0.8666666666666667


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.svm import SVC

check_svm = SVC(kernel = 'rbf')
check_svm.fit(x_train_pca, y_train)
print(check_svm.score(x_test_pca,y_test))

0.8777777777777778


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc_1 = StandardScaler()
x_scaled = sc_1.fit_transform(x)
x_test_final_scaled = sc_1.transform(x_test_final)

In [ ]:
from sklearn.decomposition import PCA
pca_1 = PCA(n_components=8)
principalComponents_train = pca_1.fit_transform(x_scaled)
principalComponents_test = pca_1.transform(x_test_final_scaled)
x_train_pca = pd.DataFrame(data = principalComponents_train)
#             , columns = ['principal component 1', 'principal component 2'])
x_test_pca = pd.DataFrame(data = principalComponents_test)
#             , columns = ['principal component 1', 'principal component 2'])

print(sum(pca.explained_variance_ratio_))

0.964246400694233


In [ ]:
model_svc = SVC(kernel = 'rbf')
model_svc.fit(x_train_pca,y)
ans = model_svc.predict(x_test_pca)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
model = GradientBoostingClassifier(learning_rate=0.05,n_estimators=100)
model.fit(x_scaled,y)
ans = model.predict(x_test_final_scaled)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
model_xgb = XGBClassifier(learning_rate=0.0005)
model_xgb.fit(x,y)
ans = model_xgb.predict(x_test_final)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
ans = pd.DataFrame(ans)
print(ans)

     0
0    0
1    1
2    0
3    0
4    1
..  ..
413  0
414  1
415  0
416  0
417  0

[418 rows x 1 columns]


In [ ]:
data_test_1 = pd.read_csv('test.csv')

In [ ]:
submission_df = pd.concat([data_test_1['PassengerId'],ans],axis=1,ignore_index=False)
print(submission_df)

     PassengerId  0
0            892  0
1            893  1
2            894  0
3            895  0
4            896  1
..           ... ..
413         1305  0
414         1306  1
415         1307  0
416         1308  0
417         1309  0

[418 rows x 2 columns]


In [ ]:
submission_df.to_csv('submit.csv')